# Generated by Django 3.2.3 on 2021-07-26 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('yes', 'Accepted'), ('no', 'Denied'), ('unsolved', 'Pending')], default='unsolved', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoomFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('files', models.FilePathField(match='.pdf', path='/files', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('initroduction', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
