# Generated by Django 3.2.3 on 2021-07-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomfiles',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
