# Generated by Django 3.2.3 on 2021-07-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
        ('team', '0003_alter_meetingroomfiles_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamcreator', to='user.user'),
        ),
    ]
