# Generated by Django 3.2.3 on 2021-07-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210728_0831'),
        ('team', '0004_alter_team_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to='user.user'),
        ),
    ]
