# Generated by Django 3.2.3 on 2021-07-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='initroduction',
            new_name='introduction',
        ),
    ]
