# Generated by Django 3.2.3 on 2021-07-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_rename_initroduction_team_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
            preserve_default=False,
        ),
    ]
