# Generated by Django 3.2.3 on 2021-08-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20210805_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomfiles',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
